//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disponibilidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disponibilidad()
        {
            this.Citas = new HashSet<Citas>();
        }
    
        public int Id_Disponibilidad { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public Nullable<int> Id_Punto { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<int> Id_Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Disponibilidad { get; set; }
        public Nullable<System.TimeSpan> Hora_Inicial { get; set; }
        public Nullable<System.TimeSpan> Hora_Fin { get; set; }
        public string Login_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_creacion { get; set; }
        public string Login_Modificacion { get; set; }
        public Nullable<System.DateTime> Fecha_Modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Puntos Puntos { get; set; }
    }
}
